### ISSUE TITLE
[Suggestion] Add message from original exceptions to the log/stacktrace

### ISSUE THREAD

**Issue by immortaleeb** [XDjackieXD/PackUpdate#2]
A friend of mine just a got an IOException while updating and he got the following log:
`Could not update: Got IOException while updating!
    at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1460)
    at at.chaosfield.packupdate.FileManager.downloadFile(FileManager.java:111)
    at at.chaosfield.packupdate.FxController$1.call(FxController.java:89)
    at at.chaosfield.packupdate.FxController$1.call(FxController.java:40)
    at javafx.concurrent.Task$TaskCallable.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Please take a look at the log for a stacktrace.`

It's nice that exceptions are caught, but the original message from the IOException is kinda lost, so its hard to figure out what went wrong :p

**Comment by XDjackieXD** [comment]
What version of PackUpdate are you using?
The current version (2.0) has a lot better error handling.

**Comment by immortaleeb** [comment]
Was running version 1.1 (check my other issue: #1)
I just tried it with version 2.0 and the error handling has indeed improved - apparently some server is down I couldn't download any files.
