### ISSUE TITLE
Crashing while loading actual PackUpdate.jar

### ISSUE THREAD

**Issue by Faeranne** [XDjackieXD/PackUpdate#8]
I tried downloading and loading up the example pack, but get the following error after PackUpdate.jar downloads:
`Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at at.chaosfield.updaterUpdater.UpdaterUpdater.<init>(UpdaterUpdater.java:57)
    at at.chaosfield.updaterUpdater.UpdaterUpdater.main(UpdaterUpdater.java:24)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 14 more`
And the following error when i try to use the old Pre-Launch Command format:
`Error: Could not find or load main class at.chaosfield.packupdate.PackUpdate`

**Comment by XDjackieXD** [comment]
Which Java version are you using? I'm using some Java 8 features for the UI which will crash with a similar error when used with older Java versions.
Also please keep in mind that I will not add any features and only fix critical bugs as the MultiMC Team is already working on a way better system for modpacks & delta updates.

**Comment by Faeranne** [comment]
My current Java version is 8, but i'm hitting the same error on Java 9 as well.
And I'm aware that they are working on it, but it's been long enough that i'm more than happy to see this project exists.

**Comment by XDjackieXD** [comment]
It looks a lot like that your packupdate jar is corrupt. the first error is that the updater updater failed at launching packupdate and the second error is basically the same. try deleting the packupdate jar so that updater updater redownloads it from github

**Comment by XDjackieXD** [comment]
closing due to inactivity. If problem still exists feel free to reopen this issue

**Comment by Faeranne** [comment]
Ended up having the issue again, and have determined the issue is using OpenJDK.

**Comment by XDjackieXD** [comment]
I'm using pretty new JavaFX features but I'm pretty sure that recent (>=8) OpenJDK versions are working as I already used thisbon my laptop. I will investigate this and reopen the bug if I can reproduce it
